Add options to enforce autoformatter version
LLNL/blt pull request #407
Opened 2020-10-05 15:28 UTC by joshessman-llnl

This PR allows projects to specify the autoformatter version they require, which could prevent situations where different tool versions could result in inconsistent changes being made between users.

2020-10-05 15:36 UTC, davidbeckingsale requested changes
One quick comment.

2020-10-05 15:36 UTC, davidbeckingsale commented on cmake/SetupCodeChecks.cmake
> +    endif()
This diff looks like you have added an unmatched endif? If not, can you fix the indenting for it.

2020-10-05 18:30 UTC, kennyweiss approved these changes
Thanks @joshessman-llnl !

2020-10-05 18:52 UTC, kennyweiss commented on cmake/SetupCodeChecks.cmake
> +        execute_process(COMMAND ${CLANGFORMAT_EXECUTABLE} --version
Addresses #397

2020-10-05 19:08 UTC, joshessman-llnl commented on RELEASE-NOTES.md
> +- Added user option for enforcing specific versions of autoformatters
Thanks for taking a look at this!  I think this should support specific versions as well as the version checks make sure that the found version "starts with" the required version.  For example, the clang-format on my machine is `10.0.0-4ubuntu1`, so a project could set `BLT_REQUIRED_CLANGFORMAT_VER` to any of `10`, `10.0`, `10.0.0`, etc and have the check succeed.

2020-10-14 22:07 UTC, white238 commented on RELEASE-NOTES.md
> +  ``BLT_REQUIRED_ASTYLE_VER``, ``BLT_REQUIRED_CLANGFORMAT_VER``, and ``BLT_REQUIRED_UNCRUSTIFY_VER``
I think on a whole (though I'm not saying we are perfect), BLT generally doesn't shorten variables names.  Can you change this to VERSION not VER?

2020-10-14 22:07 UTC, white238 commented on docs/api/code_check.rst
> +If a particular version of a code formatting tool is required, you can configure BLT to enforce
Thanks for doing the documentation!

2020-10-14 22:18 UTC, white238 approved these changes

2020-10-14 22:32 UTC, davidbeckingsale approved these changes

2020-10-14 22:33 UTC, merged