add INTELLLVM support.
LLNL/blt pull request #496
Opened 2021-05-28 17:52 UTC by robinson96

Teach BLT about the Intel LLVM OneAPI compiler.

2021-05-28 20:38 UTC, adayton1 commented on cmake/BLTMacros.cmake
> +          message("appending ${arg_GNU} to ${arg_FLAGS_VAR}")
Should this message be removed?

2021-05-28 20:39 UTC, adayton1 commented on cmake/SetupCompilerOptions.cmake
> +        message(STATUS "Fortran Compiler family is Intel")
IntelLLVM

2021-05-28 22:45 UTC, kennyweiss requested changes
Thanks @robinson96 

* Please add a line to the `RELEASE_NOTES`
* Also, does this need to be incorporated into existing usages of `blt_append_custom_compiler_flag`?
https://github.com/LLNL/blt/blob/91ba4aa22b5bcdc792d644f17c25efc94421d9fd/cmake/SetupCompilerOptions.cmake#L300-L351

2021-08-12 20:24 UTC, robinson96 commented
> 
> 
> Thanks @robinson96
> 
>     * Please add a line to the `RELEASE_NOTES`
> 
>     * Also, does this need to be incorporated into existing usages of `blt_append_custom_compiler_flag`?
>       https://github.com/LLNL/blt/blob/91ba4aa22b5bcdc792d644f17c25efc94421d9fd/cmake/SetupCompilerOptions.cmake#L300-L351

Release note added. The default values for all of those calls look to be aligned with what is necessary for IntelLLVM.

2021-08-12 20:28 UTC, adayton1 approved these changes
LGTM

2021-08-20 17:05 UTC, adayton1 commented
@kennyweiss, @white238, any more comments on this pull request, or can it be merged?

2021-08-20 19:12 UTC, white238 approved these changes

2021-08-20 19:14 UTC, white238 commented
@kennyweiss can you rereview then dismiss your change request?  After that I will create a local branch from the fork branch, it runs through the gitlab tests.

2021-08-20 19:17 UTC, kennyweiss approved these changes
Thanks @adayton1 -- I just noticed that the API docs will also need to be updated to reflect the new addition:
https://github.com/LLNL/blt/blob/develop/docs/api/utility.rst

Other than that, this should be good to go.

2021-08-20 19:21 UTC, adayton1 commented
This is on Peter's personal fork, and he's out today. If you want to just add it to the branch you'll create from his fork, that's fine. Otherwise, I'll ask him to fix the API docs when he gets back in on Monday.

2021-08-21 01:25 UTC, merged